### ISSUE TITLE
x86 emulator for PCI OpROM causes issue on latest release

### ISSUE THREAD

**Issue by Rippanda12** [radxa/edk2-platforms#6]
Commit [eafa21c9d78ede870a182d7aecf4fe1c92a07896](https://github.com/radxa/edk2-platforms/commit/eafa21c9d78ede870a182d7aecf4fe1c92a07896) makes the system throw an SError exeption at 0x0000000477833E20 when using with an AMD dGPU plugged in (Note the [32G bar size commit](https://github.com/radxa/edk2-platforms/commit/4dcd18ee1e4e8d1f5ae222044f462c4e7d231f2a) has been reverted in the bios im testing):

<img width="680" height="540" alt="Image" src="https://cdn.discordapp.com/attachments/1319155498263773214/1395800953139236996/IMG_20250718_191408214.jpg?ex=687c6d2f&is=687b1baf&hm=5731335d568d75be8f5447bf29255a0fdc6b796b4c70ffc2e1ed102b791eeb9b&" />

The latest output from UART2:
<img width="680" height="540" alt="Image" src="https://github.com/user-attachments/assets/d8b47b0a-b14c-4c82-9193-83f2e7be913b" />

**Comment by RadxaYuntian** [comment]
Can you check the 32G bar size without x86 emulator to see if previous GPU issues was caused by emulator as well?

**Comment by Rippanda12** [comment]
I just tried each commit by reverting each these 2 create issues regardless if one is not applied

**Comment by RadxaYuntian** [comment]
Should be fixed by https://github.com/radxa/edk2-non-osi/commit/9cfd7f3f1f745b1446bb240c615085384a12c7cd

**Comment by Rippanda12** [comment]
did you test? i had this applied on my [fork](https://github.com/Rippanda12/edk2-non-osi/commit/64174c6012ad9ce6a858ca7f3b89a79611e9c3f9) but still the same issue

**Comment by RadxaYuntian** [comment]
No I don't have devices to test.

**Comment by RadxaYuntian** [comment]
I'm able to boot with AMD RX550 on the latest development build:

![Image](https://github.com/user-attachments/assets/5a1193b4-048e-4f79-a673-6a9922d518aa)
